---
name: Build and Deploy

on:
  pull_request:
    types:
      - closed # roda quando o PR sincroniza/merge
    branches:
      - "master"
  workflow_run:
    workflows: [Lint and Test]
    types:
      - completed
jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "roda Deploy"
